"""
Blessing EA .set File Generator
Converts optimization results to MT4/MT5 .set format
"""

import pandas as pd
from pathlib import Path
from typing import Dict, Any
import logging

logger = logging.getLogger(__name__)


class SetFileGenerator:
    """Generate MT4/MT5 .set files from optimization results"""

    # Mapping Python config → Blessing EA parameter names
    PARAMETER_MAPPING = {
        # Entry signals (0=OFF, 1=BUY, 2=SELL)
        'ma_entry': 'MA_Entry',
        'cci_entry': 'CCI_Entry',
        'bollinger_entry': 'Bollinger_Entry',
        'stoch_entry': 'Stochastic_Entry',
        'macd_entry': 'MACD_Entry',

        # Entry logic
        'b3_traditional': 'B3_Traditional',  # True/False
        'use_any_entry': 'UseAnyEntry',      # True/False
        'force_market_cond': 'ForceMarketCond',  # 0-3

        # Grid settings (from config, not CSV)
        'base_lot': 'BaseLot',
        'lot_multiplier': 'LotMultiplier',
        'grid_step_pips': 'GridStep',
        'max_grid_levels': 'MaxLevels',
        'take_profit_pips': 'TakeProfit',

        # Risk management
        'max_drawdown_percent': 'MaxDrawdown',
        'use_autocal': 'UseAutoCal',
        'use_smartgrid': 'UseSmartGrid',

        # Timeframes
        'ma_timeframe': 'MA_Timeframe',
        'cci_timeframe': 'CCI_Timeframe',
        'bollinger_timeframe': 'Bollinger_Timeframe',
        'stoch_timeframe': 'Stochastic_Timeframe',
        'macd_timeframe': 'MACD_Timeframe',
    }

    def __init__(self, default_grid_config: Dict[str, Any] = None):
        """
        Args:
            default_grid_config: Default grid settings (base_lot, lot_multiplier, etc.)
                                If None, uses Blessing EA defaults
        """
        self.default_grid_config = default_grid_config or {
            'base_lot': 0.01,
            'lot_multiplier': 2.0,
            'grid_step_pips': 20,
            'max_grid_levels': 10,
            'take_profit_pips': 50,
            'max_drawdown_percent': 30,
            'use_autocal': True,
            'use_smartgrid': True,

            # Default timeframes (MT4/MT5 constants)
            'ma_timeframe': 60,      # H1
            'cci_timeframe': 60,     # H1
            'bollinger_timeframe': 60,  # H1
            'stoch_timeframe': 60,   # H1
            'macd_timeframe': 60,    # H1
        }

    def generate_set_file(
        self,
        config: Dict[str, Any],
        output_path: str,
        name: str = "Optimized",
        magic_number: int = 12345
    ) -> None:
        """
        Generate .set file from configuration

        Args:
            config: Configuration dict (from CSV row or optimizer)
            output_path: Path where to save .set file
            name: Configuration name (for comments)
            magic_number: EA magic number
        """
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Merge config with defaults
        full_config = {**self.default_grid_config, **config}

        lines = []
        lines.append(f"; Blessing EA Configuration: {name}")
        lines.append(f"; Generated by Blessing Optimizer")
        lines.append(f"; Score: {config.get('score', 'N/A')}")
        lines.append(f"; Win Rate: {config.get('win_rate', 'N/A')}")
        lines.append(f"; Profit Factor: {config.get('profit_factor', 'N/A')}")
        lines.append("")

        # Magic number
        lines.append(f"MagicNumber={magic_number}")
        lines.append("")

        # Entry signals
        lines.append("; Entry Signals (0=OFF, 1=BUY, 2=SELL)")
        for key in ['ma_entry', 'cci_entry', 'bollinger_entry', 'stoch_entry', 'macd_entry']:
            if key in full_config:
                param_name = self.PARAMETER_MAPPING[key]
                value = full_config[key]
                lines.append(f"{param_name}={value}")
        lines.append("")

        # Entry logic
        lines.append("; Entry Logic")
        for key in ['b3_traditional', 'use_any_entry', 'force_market_cond']:
            if key in full_config:
                param_name = self.PARAMETER_MAPPING[key]
                value = full_config[key]
                # Convert bool to 1/0
                if isinstance(value, bool):
                    value = 1 if value else 0
                lines.append(f"{param_name}={value}")
        lines.append("")

        # Grid settings
        lines.append("; Grid Settings")
        for key in ['base_lot', 'lot_multiplier', 'grid_step_pips', 'max_grid_levels', 'take_profit_pips']:
            if key in full_config:
                param_name = self.PARAMETER_MAPPING[key]
                value = full_config[key]
                lines.append(f"{param_name}={value}")
        lines.append("")

        # Risk management
        lines.append("; Risk Management")
        for key in ['max_drawdown_percent', 'use_autocal', 'use_smartgrid']:
            if key in full_config:
                param_name = self.PARAMETER_MAPPING[key]
                value = full_config[key]
                if isinstance(value, bool):
                    value = 1 if value else 0
                lines.append(f"{param_name}={value}")
        lines.append("")

        # Timeframes
        lines.append("; Indicator Timeframes (1=M1, 5=M5, 15=M15, 60=H1, 240=H4, 1440=D1)")
        for key in ['ma_timeframe', 'cci_timeframe', 'bollinger_timeframe', 'stoch_timeframe', 'macd_timeframe']:
            if key in full_config:
                param_name = self.PARAMETER_MAPPING[key]
                value = full_config[key]
                lines.append(f"{param_name}={value}")

        # Write file
        content = "\n".join(lines)
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(content)

        logger.info(f"[SET] Generated: {output_path}")

    def generate_top_n_from_csv(
        self,
        csv_path: str,
        output_dir: str,
        top_n: int = 10,
        magic_number_start: int = 10000
    ) -> None:
        """
        Generate .set files for top N configurations from CSV

        Args:
            csv_path: Path to optimization results CSV
            output_dir: Directory where to save .set files
            top_n: Number of top configurations to export
            magic_number_start: Starting magic number (increments by 1 for each config)
        """
        df = pd.read_csv(csv_path)
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        logger.info(f"[SET] Generating top {top_n} configurations from {csv_path}")

        for i in range(min(top_n, len(df))):
            row = df.iloc[i]
            config = row.to_dict()

            # Create filename
            rank = i + 1
            score = config.get('score', 0)
            win_rate = config.get('win_rate', 0)
            filename = f"blessing_rank{rank:02d}_score{int(score)}_wr{int(win_rate*100)}.set"
            output_path = output_dir / filename

            # Generate .set file
            self.generate_set_file(
                config=config,
                output_path=str(output_path),
                name=f"Rank #{rank}",
                magic_number=magic_number_start + i
            )

        logger.info(f"[SET] Generated {min(top_n, len(df))} .set files in {output_dir}")


def main():
    """Example usage"""
    import argparse

    parser = argparse.ArgumentParser(description='Generate MT4/MT5 .set files from optimization results')
    parser.add_argument('--csv', type=str, required=True,
                       help='Path to optimization results CSV')
    parser.add_argument('--output-dir', type=str, default='./set_files',
                       help='Output directory for .set files')
    parser.add_argument('--top-n', type=int, default=10,
                       help='Number of top configurations to export (default: 10)')
    parser.add_argument('--magic-start', type=int, default=10000,
                       help='Starting magic number (default: 10000)')

    # Grid settings (optional overrides)
    parser.add_argument('--base-lot', type=float, default=0.01,
                       help='Base lot size (default: 0.01)')
    parser.add_argument('--lot-multiplier', type=float, default=2.0,
                       help='Lot multiplier (default: 2.0)')
    parser.add_argument('--grid-step', type=int, default=20,
                       help='Grid step in pips (default: 20)')
    parser.add_argument('--max-levels', type=int, default=10,
                       help='Max grid levels (default: 10)')
    parser.add_argument('--take-profit', type=int, default=50,
                       help='Take profit in pips (default: 50)')

    args = parser.parse_args()

    # Setup logging
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(levelname)s - %(message)s'
    )

    # Create generator with custom grid settings
    grid_config = {
        'base_lot': args.base_lot,
        'lot_multiplier': args.lot_multiplier,
        'grid_step_pips': args.grid_step,
        'max_grid_levels': args.max_levels,
        'take_profit_pips': args.take_profit,
        'max_drawdown_percent': 30,
        'use_autocal': True,
        'use_smartgrid': True,
        'ma_timeframe': 60,
        'cci_timeframe': 60,
        'bollinger_timeframe': 60,
        'stoch_timeframe': 60,
        'macd_timeframe': 60,
    }

    generator = SetFileGenerator(default_grid_config=grid_config)

    # Generate .set files
    generator.generate_top_n_from_csv(
        csv_path=args.csv,
        output_dir=args.output_dir,
        top_n=args.top_n,
        magic_number_start=args.magic_start
    )

    print(f"\n✅ Generated {args.top_n} .set files in {args.output_dir}")
    print(f"📂 Copy them to: MT4/MT5/MQL4/Presets/ or MT4/MT5/MQL5/Presets/")


if __name__ == '__main__':
    main()
